version: '3.8'

services:
  # Development Service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    

    depends_on:
      - mssql
    restart: on-failure

    networks:
      - nest-network
  
    volumes:
      - .:/app
      - /app/node_modules
   
    profiles:
      - dev
      

    command: >
      sh -c "
        echo 'Waiting for MSSQL to be ready...' &&
        sleep 10 &&
        npx prisma migrate dev &&
        npm run start:dev
      "

  # Production Service
  app-prod:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "8080:3000"
    
    restart: on-failure
    
        
        
    profiles:
      - prod
    networks:
      - nest-network
  
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/src/main.js
      "


  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nestjs-mssql
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "MyS3cure@Pwd"
      ACCEPT_EULA: "Y"
  
      
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - nest-network
  


volumes:
  mssql-data:

networks:
  nest-network:
    driver: bridge


