FROM node:24-slim
RUN apt-get update && apt-get install -y openssl ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma
COPY .env.dev .env          
RUN npx prisma generate     

COPY . .

ENV NODE_ENV=dev
CMD ["npm", "run", "start:dev"]
