services:
  # Development Service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  # Production Service
  app-prod:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - "8080:3000"
    depends_on:
      - db
    profiles:
      - prod

  # Database Service (Postgres)
  db:
    image: postgres:17-alpine
    container_name: nest-js-db
    ports:
      - "5432:5432"
    env_file:
      - .env.dev 
    volumes:
      - db-data:/var/lib/postgresql/data

  # Optional PgAdmin (for DB viewing)
  pgadmin:
    image: dpage/pgadmin4
    container_name: nestjs-pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db-data:
